bioproject: "PRJNA729801"

site_pattern: "HTP"

project: wastewater-viromics-takehome

paths:
  sample_sheet: config/samples_htp.csv
  raw_dir: data/raw/htp
  host_reference: resources/host/human/GRCh38.primary_assembly.genome.fa.gz

download:
  threads: 8